/*
 * This file is generated by jOOQ.
*/
package generated_resources.tables;


import generated_resources.Test;
import generated_resources.tables.records.GuildSettingsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildSettings extends TableImpl<GuildSettingsRecord> {

    private static final long serialVersionUID = 95799120;

    /**
     * The reference instance of <code>test.guild_settings</code>
     */
    public static final GuildSettings GUILD_SETTINGS = new GuildSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuildSettingsRecord> getRecordType() {
        return GuildSettingsRecord.class;
    }

    /**
     * The column <code>test.guild_settings.id</code>.
     */
    public final TableField<GuildSettingsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(22).nullable(false), this, "");

    /**
     * The column <code>test.guild_settings.landing_channel</code>.
     */
    public final TableField<GuildSettingsRecord, String> LANDING_CHANNEL = createField("landing_channel", org.jooq.impl.SQLDataType.VARCHAR(22).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>test.guild_settings.log_channel</code>.
     */
    public final TableField<GuildSettingsRecord, String> LOG_CHANNEL = createField("log_channel", org.jooq.impl.SQLDataType.VARCHAR(22).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>test.guild_settings</code> table reference
     */
    public GuildSettings() {
        this(DSL.name("guild_settings"), null);
    }

    /**
     * Create an aliased <code>test.guild_settings</code> table reference
     */
    public GuildSettings(String alias) {
        this(DSL.name(alias), GUILD_SETTINGS);
    }

    /**
     * Create an aliased <code>test.guild_settings</code> table reference
     */
    public GuildSettings(Name alias) {
        this(alias, GUILD_SETTINGS);
    }

    private GuildSettings(Name alias, Table<GuildSettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuildSettings(Name alias, Table<GuildSettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildSettings as(String alias) {
        return new GuildSettings(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildSettings as(Name alias) {
        return new GuildSettings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildSettings rename(String name) {
        return new GuildSettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildSettings rename(Name name) {
        return new GuildSettings(name, null);
    }
}
