/*
 * This file is generated by jOOQ.
*/
package generated_resources;


import generated_resources.tables.AdminUsers;
import generated_resources.tables.GuildSettings;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.admin_users</code>.
     */
    public static final AdminUsers ADMIN_USERS = generated_resources.tables.AdminUsers.ADMIN_USERS;

    /**
     * The table <code>test.guild_settings</code>.
     */
    public static final GuildSettings GUILD_SETTINGS = generated_resources.tables.GuildSettings.GUILD_SETTINGS;
}
