/*
 * This file is generated by jOOQ.
*/
package generated_resources;


import generated_resources.tables.AdminUsers;
import generated_resources.tables.GuildSettings;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = -1042983924;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.admin_users</code>.
     */
    public final AdminUsers ADMIN_USERS = generated_resources.tables.AdminUsers.ADMIN_USERS;

    /**
     * The table <code>test.guild_settings</code>.
     */
    public final GuildSettings GUILD_SETTINGS = generated_resources.tables.GuildSettings.GUILD_SETTINGS;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AdminUsers.ADMIN_USERS,
            GuildSettings.GUILD_SETTINGS);
    }
}
