/*
 * This file is generated by jOOQ.
*/
package generated_resources.tables.records;


import generated_resources.tables.GuildSettings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildSettingsRecord extends TableRecordImpl<GuildSettingsRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -88364842;

    /**
     * Setter for <code>test.guild_settings.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.guild_settings.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test.guild_settings.landing_channel</code>.
     */
    public void setLandingChannel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.guild_settings.landing_channel</code>.
     */
    public String getLandingChannel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.guild_settings.log_channel</code>.
     */
    public void setLogChannel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.guild_settings.log_channel</code>.
     */
    public String getLogChannel() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GuildSettings.GUILD_SETTINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GuildSettings.GUILD_SETTINGS.LANDING_CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GuildSettings.GUILD_SETTINGS.LOG_CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLandingChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLogChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLandingChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLogChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildSettingsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildSettingsRecord value2(String value) {
        setLandingChannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildSettingsRecord value3(String value) {
        setLogChannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildSettingsRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildSettingsRecord
     */
    public GuildSettingsRecord() {
        super(GuildSettings.GUILD_SETTINGS);
    }

    /**
     * Create a detached, initialised GuildSettingsRecord
     */
    public GuildSettingsRecord(String id, String landingChannel, String logChannel) {
        super(GuildSettings.GUILD_SETTINGS);

        set(0, id);
        set(1, landingChannel);
        set(2, logChannel);
    }
}
